# Gumiho System 九尾狐系统是一个用于产生更准确,高质量的人工智能翻译文本的系统
# 本系统模拟人类翻译过程,将ai的翻译拆分为初译,校对,润色等阶段,提供自动生成人名/专有名词字典,自动生成文本总结,自动生成历史文本总结并利用等功能
# Gumiho System会通过用户设置,自动生成各阶段的ai请求prompt,要求ai进行结构化输出,并将其处理保存,方便下一阶段的翻译工作和后期的人工精修

#----------------------------项目基本设置----------------------------
Translation Project Name: default
Translater:
  - "Gumiho System"
type: Novel # 项目类型,可选Novel,game,video,默认为novel
original language: Japanese # 原文语言
target language: Chinese #目标语言
book content summary: | # 已知的书籍内容简介,可选
Writing style: | # 书籍风格,可选

#需要翻译的源文件的格式，支持json，sql（默认为来自lunatranslate的结构），excel，docs，txt
Original format: 

ai_setting:
  Azure: #Azure翻译设置
    endpoint: None
    api: None
    key: None
  Openai: #Openai翻译设置
    api: None
    key: None
  local1: #本地模型1设置
    api: None
    key: None
  local2: #本地模型1设置
    api: None
    key: None
  local3:
    # .....

#需要的翻译任务
first_translation_needed: true #是否需要初译
Proofreading_needed: true #是否需要校对


#----------------------------书籍基本设置----------------------------

book/game/video Name: default # 书籍/游戏/视频名称
book content summary: | # 已知的书籍内容简介,可选
Writing style: | # 书籍风格,可选



#----------------------------项目初译设置----------------------------
first_translation_setting:
  sentence-by-sentence_translation: false #启用逐句翻译模式,不启用时默认为整合翻译模式
  Number of texts per group: 30 #启用整合翻译模式时,每组文本的数量
  enable contents: false #存在/启用章节表

  human_involvement: true #是否需要人工参与
  human_check_setting: #人工参与设置,设定人工参与的部分,human_involvement: true时生效
    summary_check: true #是否需要人工检查总结

  #历史文本利用与总结优化
  Automatically generated text summary:
    create: true #设置为true时,自动生成文本总结
    using: true #设置为true时,自动利用历史文本总结
    Number of history generated records: 5 #自动利用的历史记录数量,不启用时默认为零
    Number of historical texts used: 0 #加入上文的历史文本原文数量,不启用时默认为零

  #人名/专有名词翻译设置
  Proper noun translation: true # 设置为true时,翻译,设置为false时,所有人名和专有名词保留原文
  Automatic Translation Dictionary: true #设置为true时,自动生成专有名词对照翻译词典  

  #用于初译的prompt文本
  base_prompt: |
    请将给出的文本翻译为对应的简体中文
    要求准确,通顺,译文符合中文的表达习惯

  #用于指定初译时ai结构化输出的样例json格式
  first_trans_json: |



#----------------------------项目校对设置----------------------------
proofreading_setting:
  #用于指定校对的prompt文本
  proofreading_prompt: |
    你需要执行一个轻小说的校对任务
    根据给出的日中对照的译文文本,上下文,和给出的与小说有关的其他信息,对照检查表,一句句检查原翻译是否存在错误是否存在更合适的翻译,并按格式要求输出.

  Enable Contents: false #存在/启用章节表

  #用于指定ai结构化输出的样例json格式
  novel_Proofreading_json: |

  #人名/专有名词翻译设置
  Proper noun translation: true # 设置为true时,翻译,设置为false时,所有人名和专有名词保留原文
  Automatic Translation Dictionary: true #设置为true时,自动生成对照翻译词典  

  #历史文本利用与总结优化
  Automatically generated text summary:
    enable: true #设置为true时,自动生成文本总结
    Number of history generated records: 5 #自动利用的历史记录组数,不启用时默认为零
    Number of historical texts used: 0 #加入上文的历史文本原文组数,不启用时默认为零
  Number of texts per group: 30 #每组文本的数量
  Checklist: | #校对检查表
    1.请校对是否按照专有名词字典正确翻译
    2.请根据上下文校对是否存在人称代词问题（错用，乱加，主宾混淆，男女不分等）问题
    3.是否有其他更好的用词,翻译等













#这里指定了翻译对象为.sqlite,即兼容lunaTranslator翻译记录的处理模式
luna_fomat_setting:
  Number of texts per group: 30 #每组文本的数量(每个id下为"一个"文本)
  Character existence: true # 是否存在人物信息,当该选项设置为true时,如果文本前存在"人物+换行符"将会被识别为这条文本的来源人物,若不存在,则视为旁白
  Update character/proper noun dictionary: true # 是否更新人物/专有名词字典,当该选项设置为true时,如果发现了新的人物,将会询问使用者是否更新人物字典,如果设置为false,人物栏将默认为"其他角色"

Novel translation setting:
  max_len_num: 200